services:
  mariadb:
    image: mariadb:lts
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
  #   - ./mariadb_data:/var/lib/mysql
      - mariadb-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword123
   #  MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_DATABASE: mydatabase
      MARIADB_USER: myuser
      MARIADB_PASSWORD: userpassword123
    networks:
      - default
    # - custom-network

    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p$${MARIADB_ROOT_PASSWORD}", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb-data:
    driver: local

networks:
  default:
    driver: bridge
# custom-network:
#   external: true

