services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
  #   - ./mysql_data:/var/lib/mysql
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
   #  MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: userpassword123
    networks:
      - default
    # - custom-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
    driver: local

networks:
  default:
    driver: bridge
# custom-network:
#   external: true


